/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    // "aws_cognito_identity_pool_id": "us-east-2:5ee61e83-3065-4062-b424-f42d36b036d4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_bI2LCELfb",
    "aws_user_pools_web_client_id": "63sehr8m99ls09f0eqlm247mem",
    "oauth": {}
};


export default awsmobile;