/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_bI2LCELfb",
    "aws_user_pools_web_client_id": "63sehr8m99ls09f0eqlm247mem",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7dge6qoxzbe3tmaricno4qyufi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rh5nehve6nhw7ina3fa5zaoa7e",
    "aws_cloud_logic_custom": [
        {
            "name": "threadAPI",
            "endpoint": "https://4joy85d5dd.execute-api.us-east-2.amazonaws.com/staging",
            "region": "us-east-2"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "ThreadsTable-staging",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
