/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_zXofi8dKe",
    "aws_user_pools_web_client_id": "7q3rdm35mka8q7hhtouf699eh8",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://beha3zttxvdn3c5p3ekrsfau7u.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-oawykrfcffcftc4axfbrnz2mny",
    "aws_cloud_logic_custom": [
        {
            "name": "threadAPI",
            "endpoint": "https://9j4xprmsid.execute-api.us-east-2.amazonaws.com/dev",
            "region": "us-east-2"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "ThreadsTable-dev",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
